name: Deploy Wiki
on:
  push:
    paths:
      # Trigger only when wiki directory changes
      - '.github/wiki/**'
    branches: [main]
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Andrew-Chen-Wang/github-wiki-action@v4
      with:
        path: .github/wiki
