name: Publish docs to Wiki


# Trigger this action only if there are changes pushed to the docs/** directory under the main branch
on:
  push:
    paths:
      - wiki/** # This includes all sub folders
    branches:
      - main # This can be changed to any branch of your preference
jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    steps:  
      - name: Publish Github Wiki
        uses: nimblehq/publish-github-wiki-action@v1.0
        with:
          user_name: yorkshire-pudding
          user_email: github@systemhorizons.co.uk
          user_access_token: ${{ secrets.WIKI_ACTION_TOKEN }}


